### ISSUE TITLE
bug: ipo detail page is not working

### ISSUE THREAD

**Issue by LeoHChen** [storyprotocol/protocol-explorer-app#4]
https://explorer.storyprotocol.xyz/ipo/0xa8c41f0a54828a4a792c054bf7b255d514e16e16

<img width="844" alt="image" src="https://github.com/storyprotocol/protocol-explorer-app/assets/4513927/147a8156-8ed4-4c56-88e4-73cac925311e">

**Comment by DonFungible** [comment]
Fixed due to outdated env var on production. However this will still show up if that IP Org ID is not valid. Create a new issue to address that:  https://github.com/storyprotocol/protocol-explorer-app/issues/5
